apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
data:
  htpasswd: >-
    YnVzeTokMnkkMDUkSy55SDdCaDkvYjVZdzdZVEgxWGp2dU4veVRXbUVhOXlLQnJzNWs2azZzL3M1cFA1M1NHeGkKCg==
type: Opaque